# Selection Colors
selection_foreground     #c4a7e7
selection_background     #47086c


# Window border Colors
active_border_color      #9b6dd6
inactive_border_color    #2b043f

# Kitty tabs colors 
active_tab_foreground    #c4a7e7
active_tab_background    #6a1fa0

inactive_tab_foreground  #7f3fbf
inactive_tab_background  #3a0656

# Basic color
background               #2b043f
foreground               #c4a7e7

# 16 main colors
color0   #2b043f
color1   #3a0656
color2   #47086c
color3   #570b8a
color4   #6a1fa0
color5   #7f3fbf
color6   #9b6dd6
color7   #c4a7e7

color8   #3a0656
color9   #47086c
color10  #570b8a
color11  #6a1fa0
color12  #7f3fbf
color13  #9b6dd6
color14  #c4a7e7
color15  #e9ddff

# Cursor colors
cursor                   #9b6dd6
cursor_text_color        #2b043f

# Url color
url_color                #7f3fbf
