# VPN tab with horizontal split
new_tab VPN
layout splits
launch sh -c "fastfetch; exec $SHELL" 
launch --location=hsplit --bias=30
focus

# Other tabs
new_tab T1
launch

new_tab T2
launch

new_tab T3
launch

new_tab T4
launch
